Array Transposition

In [1]:
import numpy as np

In [2]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [5]:
arr=np.random.rand(6,3)
arr

array([[0.62068025, 0.06770541, 0.67556469],
       [0.40771912, 0.51297881, 0.63587812],
       [0.58579194, 0.43670368, 0.02972708],
       [0.96456996, 0.45920875, 0.71262941],
       [0.69810195, 0.87662713, 0.54656037],
       [0.69354907, 0.61819343, 0.87333198]])

In [6]:
np.dot(arr.T, arr)

array([[2.79338288, 1.99065372, 2.37061756],
       [1.99065372, 1.8199523 , 1.73117672],
       [2.37061756, 1.73117672, 2.43088999]])

In [ ]:
arr=np.arange(16).reshape(2,2,4)

In [ ]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])